// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: resender/protob/protob.proto

package protob

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatFileServiceClient is the client API for ChatFileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatFileServiceClient interface {
	RequestRespond(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error)
	TransferChunks(ctx context.Context, opts ...grpc.CallOption) (ChatFileService_TransferChunksClient, error)
	DownloadChunks(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (ChatFileService_DownloadChunksClient, error)
	KeepInfoUpdated(ctx context.Context, in *KeepUpdatedRequest, opts ...grpc.CallOption) (ChatFileService_KeepInfoUpdatedClient, error)
	UploadChatMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	GetMessageSequence(ctx context.Context, opts ...grpc.CallOption) (ChatFileService_GetMessageSequenceClient, error)
	UpdateSharedTypingInfo(ctx context.Context, in *UserTypingInfo, opts ...grpc.CallOption) (*empty.Empty, error)
	BroadcastSharedTypingInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ChatFileService_BroadcastSharedTypingInfoClient, error)
}

type chatFileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatFileServiceClient(cc grpc.ClientConnInterface) ChatFileServiceClient {
	return &chatFileServiceClient{cc}
}

func (c *chatFileServiceClient) RequestRespond(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error) {
	out := new(FileUploadResponse)
	err := c.cc.Invoke(ctx, "/transport.ChatFileService/RequestRespond", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatFileServiceClient) TransferChunks(ctx context.Context, opts ...grpc.CallOption) (ChatFileService_TransferChunksClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatFileService_ServiceDesc.Streams[0], "/transport.ChatFileService/TransferChunks", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatFileServiceTransferChunksClient{stream}
	return x, nil
}

type ChatFileService_TransferChunksClient interface {
	Send(*FileContentChunk) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type chatFileServiceTransferChunksClient struct {
	grpc.ClientStream
}

func (x *chatFileServiceTransferChunksClient) Send(m *FileContentChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatFileServiceTransferChunksClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatFileServiceClient) DownloadChunks(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (ChatFileService_DownloadChunksClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatFileService_ServiceDesc.Streams[1], "/transport.ChatFileService/DownloadChunks", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatFileServiceDownloadChunksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatFileService_DownloadChunksClient interface {
	Recv() (*FileContentChunk, error)
	grpc.ClientStream
}

type chatFileServiceDownloadChunksClient struct {
	grpc.ClientStream
}

func (x *chatFileServiceDownloadChunksClient) Recv() (*FileContentChunk, error) {
	m := new(FileContentChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatFileServiceClient) KeepInfoUpdated(ctx context.Context, in *KeepUpdatedRequest, opts ...grpc.CallOption) (ChatFileService_KeepInfoUpdatedClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatFileService_ServiceDesc.Streams[2], "/transport.ChatFileService/KeepInfoUpdated", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatFileServiceKeepInfoUpdatedClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatFileService_KeepInfoUpdatedClient interface {
	Recv() (*KnownFileInfo, error)
	grpc.ClientStream
}

type chatFileServiceKeepInfoUpdatedClient struct {
	grpc.ClientStream
}

func (x *chatFileServiceKeepInfoUpdatedClient) Recv() (*KnownFileInfo, error) {
	m := new(KnownFileInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatFileServiceClient) UploadChatMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/transport.ChatFileService/UploadChatMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatFileServiceClient) GetMessageSequence(ctx context.Context, opts ...grpc.CallOption) (ChatFileService_GetMessageSequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatFileService_ServiceDesc.Streams[3], "/transport.ChatFileService/GetMessageSequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatFileServiceGetMessageSequenceClient{stream}
	return x, nil
}

type ChatFileService_GetMessageSequenceClient interface {
	Send(*ChatMessageRequest) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatFileServiceGetMessageSequenceClient struct {
	grpc.ClientStream
}

func (x *chatFileServiceGetMessageSequenceClient) Send(m *ChatMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatFileServiceGetMessageSequenceClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatFileServiceClient) UpdateSharedTypingInfo(ctx context.Context, in *UserTypingInfo, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/transport.ChatFileService/UpdateSharedTypingInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatFileServiceClient) BroadcastSharedTypingInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ChatFileService_BroadcastSharedTypingInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatFileService_ServiceDesc.Streams[4], "/transport.ChatFileService/BroadcastSharedTypingInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatFileServiceBroadcastSharedTypingInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatFileService_BroadcastSharedTypingInfoClient interface {
	Recv() (*UserTypingInfo, error)
	grpc.ClientStream
}

type chatFileServiceBroadcastSharedTypingInfoClient struct {
	grpc.ClientStream
}

func (x *chatFileServiceBroadcastSharedTypingInfoClient) Recv() (*UserTypingInfo, error) {
	m := new(UserTypingInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatFileServiceServer is the server API for ChatFileService service.
// All implementations must embed UnimplementedChatFileServiceServer
// for forward compatibility
type ChatFileServiceServer interface {
	RequestRespond(context.Context, *FileUploadRequest) (*FileUploadResponse, error)
	TransferChunks(ChatFileService_TransferChunksServer) error
	DownloadChunks(*FileDownloadRequest, ChatFileService_DownloadChunksServer) error
	KeepInfoUpdated(*KeepUpdatedRequest, ChatFileService_KeepInfoUpdatedServer) error
	UploadChatMessage(context.Context, *ChatMessage) (*empty.Empty, error)
	GetMessageSequence(ChatFileService_GetMessageSequenceServer) error
	UpdateSharedTypingInfo(context.Context, *UserTypingInfo) (*empty.Empty, error)
	BroadcastSharedTypingInfo(*empty.Empty, ChatFileService_BroadcastSharedTypingInfoServer) error
	mustEmbedUnimplementedChatFileServiceServer()
}

// UnimplementedChatFileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatFileServiceServer struct {
}

func (UnimplementedChatFileServiceServer) RequestRespond(context.Context, *FileUploadRequest) (*FileUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRespond not implemented")
}
func (UnimplementedChatFileServiceServer) TransferChunks(ChatFileService_TransferChunksServer) error {
	return status.Errorf(codes.Unimplemented, "method TransferChunks not implemented")
}
func (UnimplementedChatFileServiceServer) DownloadChunks(*FileDownloadRequest, ChatFileService_DownloadChunksServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadChunks not implemented")
}
func (UnimplementedChatFileServiceServer) KeepInfoUpdated(*KeepUpdatedRequest, ChatFileService_KeepInfoUpdatedServer) error {
	return status.Errorf(codes.Unimplemented, "method KeepInfoUpdated not implemented")
}
func (UnimplementedChatFileServiceServer) UploadChatMessage(context.Context, *ChatMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadChatMessage not implemented")
}
func (UnimplementedChatFileServiceServer) GetMessageSequence(ChatFileService_GetMessageSequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMessageSequence not implemented")
}
func (UnimplementedChatFileServiceServer) UpdateSharedTypingInfo(context.Context, *UserTypingInfo) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSharedTypingInfo not implemented")
}
func (UnimplementedChatFileServiceServer) BroadcastSharedTypingInfo(*empty.Empty, ChatFileService_BroadcastSharedTypingInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadcastSharedTypingInfo not implemented")
}
func (UnimplementedChatFileServiceServer) mustEmbedUnimplementedChatFileServiceServer() {}

// UnsafeChatFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatFileServiceServer will
// result in compilation errors.
type UnsafeChatFileServiceServer interface {
	mustEmbedUnimplementedChatFileServiceServer()
}

func RegisterChatFileServiceServer(s grpc.ServiceRegistrar, srv ChatFileServiceServer) {
	s.RegisterService(&ChatFileService_ServiceDesc, srv)
}

func _ChatFileService_RequestRespond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatFileServiceServer).RequestRespond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.ChatFileService/RequestRespond",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatFileServiceServer).RequestRespond(ctx, req.(*FileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatFileService_TransferChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatFileServiceServer).TransferChunks(&chatFileServiceTransferChunksServer{stream})
}

type ChatFileService_TransferChunksServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*FileContentChunk, error)
	grpc.ServerStream
}

type chatFileServiceTransferChunksServer struct {
	grpc.ServerStream
}

func (x *chatFileServiceTransferChunksServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatFileServiceTransferChunksServer) Recv() (*FileContentChunk, error) {
	m := new(FileContentChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatFileService_DownloadChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatFileServiceServer).DownloadChunks(m, &chatFileServiceDownloadChunksServer{stream})
}

type ChatFileService_DownloadChunksServer interface {
	Send(*FileContentChunk) error
	grpc.ServerStream
}

type chatFileServiceDownloadChunksServer struct {
	grpc.ServerStream
}

func (x *chatFileServiceDownloadChunksServer) Send(m *FileContentChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatFileService_KeepInfoUpdated_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeepUpdatedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatFileServiceServer).KeepInfoUpdated(m, &chatFileServiceKeepInfoUpdatedServer{stream})
}

type ChatFileService_KeepInfoUpdatedServer interface {
	Send(*KnownFileInfo) error
	grpc.ServerStream
}

type chatFileServiceKeepInfoUpdatedServer struct {
	grpc.ServerStream
}

func (x *chatFileServiceKeepInfoUpdatedServer) Send(m *KnownFileInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatFileService_UploadChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatFileServiceServer).UploadChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.ChatFileService/UploadChatMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatFileServiceServer).UploadChatMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatFileService_GetMessageSequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatFileServiceServer).GetMessageSequence(&chatFileServiceGetMessageSequenceServer{stream})
}

type ChatFileService_GetMessageSequenceServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessageRequest, error)
	grpc.ServerStream
}

type chatFileServiceGetMessageSequenceServer struct {
	grpc.ServerStream
}

func (x *chatFileServiceGetMessageSequenceServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatFileServiceGetMessageSequenceServer) Recv() (*ChatMessageRequest, error) {
	m := new(ChatMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatFileService_UpdateSharedTypingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTypingInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatFileServiceServer).UpdateSharedTypingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.ChatFileService/UpdateSharedTypingInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatFileServiceServer).UpdateSharedTypingInfo(ctx, req.(*UserTypingInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatFileService_BroadcastSharedTypingInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatFileServiceServer).BroadcastSharedTypingInfo(m, &chatFileServiceBroadcastSharedTypingInfoServer{stream})
}

type ChatFileService_BroadcastSharedTypingInfoServer interface {
	Send(*UserTypingInfo) error
	grpc.ServerStream
}

type chatFileServiceBroadcastSharedTypingInfoServer struct {
	grpc.ServerStream
}

func (x *chatFileServiceBroadcastSharedTypingInfoServer) Send(m *UserTypingInfo) error {
	return x.ServerStream.SendMsg(m)
}

// ChatFileService_ServiceDesc is the grpc.ServiceDesc for ChatFileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatFileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transport.ChatFileService",
	HandlerType: (*ChatFileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRespond",
			Handler:    _ChatFileService_RequestRespond_Handler,
		},
		{
			MethodName: "UploadChatMessage",
			Handler:    _ChatFileService_UploadChatMessage_Handler,
		},
		{
			MethodName: "UpdateSharedTypingInfo",
			Handler:    _ChatFileService_UpdateSharedTypingInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferChunks",
			Handler:       _ChatFileService_TransferChunks_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadChunks",
			Handler:       _ChatFileService_DownloadChunks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "KeepInfoUpdated",
			Handler:       _ChatFileService_KeepInfoUpdated_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetMessageSequence",
			Handler:       _ChatFileService_GetMessageSequence_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "BroadcastSharedTypingInfo",
			Handler:       _ChatFileService_BroadcastSharedTypingInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "resender/protob/protob.proto",
}
